In [3]:
# MOMISH intervention plots — SDR_output_Aug_11_9am
# 4 counties, implementation-index scenarios (base/current/moderate/high)
# includes combined ("All") package scenarios
# adapted from MOMISH_Plots5.ipynb

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo

In [5]:
# =========================================================
# USER SETTINGS
# =========================================================

RUN_INTERVENTIONS = {
    "mentors": True,
    "prompts": True,
    "fqa": True,
    "pulse": True,
    "referral": True,
    "blood": True,
    "combined": True,
}

BASE_DIR = Path()

DATA_ROOT = BASE_DIR 
PLOTS_ROOT = BASE_DIR

COUNTY_FOLDER_SLUGS = {
    "Kakamega": "kakamega",
    "Kisii": "kisii",
    "Mombasa": "mombasa",
    "Makueni": "makueni",
}

COUNTIES = list(COUNTY_FOLDER_SLUGS.keys())

COUNTY_DIRS = {
    county: DATA_ROOT / f"scenario_comparison_results_{slug}"
    for county, slug in COUNTY_FOLDER_SLUGS.items()
}

CANONICAL_SCENARIO_FILES = {
    "scenario_definitions.csv",
    "scenario_run_results.csv",
    "scenario_location_run_results.csv",
    "scenario_mean_results.csv",
}

def resolve_county_csv(county_dir: Path, filename: str) -> Path:
    """Resolve current canonical scenario_comparison.py output files only."""
    if filename not in CANONICAL_SCENARIO_FILES:
        raise ValueError(f"Unexpected scenario output filename: {filename}")
    path = county_dir / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing {filename} under {county_dir}")
    return path

SCENARIO_PREFIX = {
    "mentors": "mentors",
    "prompts": "prompts",
    "fqa": "fqa",
    "pulse": "pulse",
    "referral": "referral",
    "blood": "blood",
    "combined": "combined",
}

scenario_definitions_df = pd.concat(
    [
        pd.read_csv(resolve_county_csv(county_dir, "scenario_definitions.csv")).assign(County=county)
        for county, county_dir in COUNTY_DIRS.items()
    ],
    ignore_index=True,
)
scenario_definitions_df.columns = scenario_definitions_df.columns.str.strip()


def intervention_name_from_metadata(file_key):
    prefix = SCENARIO_PREFIX[file_key]
    names = (
        scenario_definitions_df.loc[
            scenario_definitions_df["scenario"].str.startswith(f"{prefix}_"),
            "intervention",
        ]
        .dropna()
        .unique()
    )
    if len(names) != 1:
        raise ValueError(f"Expected one intervention name for {file_key}; found {list(names)}")
    return names[0]

STANDARD_LEVELS = ["base", "current", "moderate", "high"]

LEVEL_TO_LABEL = {
    "base": "Baseline",
    "current": "Current",
    "moderate": "Moderate",
    "high": "High",
}

CHANGE_LEVELS = ["current", "moderate", "high"]
CHANGE_LEVEL_LABELS = [LEVEL_TO_LABEL[l] for l in CHANGE_LEVELS]

SCENARIOS = [LEVEL_TO_LABEL[l] for l in STANDARD_LEVELS]

EXCLUDE_FIRST_N_RUNS = 0
MIN_INCLUDED_RUN = EXCLUDE_FIRST_N_RUNS + 1

BASE_OUTCOMES = [
    {
        "summary_name": "Maternal mortality ratio",
        "outcome_col": "maternal_deaths_per_100k",
        "multiplier": 1,
        "ylabel": "MMR per 100,000 live births",
        "plot_name": "maternal_mortality_ratio",
        "lower_is_better": True,
    },
    {
        "summary_name": "Maternal complications",
        "outcome_col": "severe_complication",
        "multiplier": 100,
        "ylabel": "Maternal complications (%)",
        "plot_name": "maternal_complications",
        "lower_is_better": True,
    },
]

INTERVENTION_CONFIGS = {
    "mentors": {
        "intervention_name": intervention_name_from_metadata("mentors"),
        "outcomes_to_plot": BASE_OUTCOMES,
    },
    "prompts": {
        "intervention_name": intervention_name_from_metadata("prompts"),
        "outcomes_to_plot": BASE_OUTCOMES + [
            {
                "summary_name": "Antenatal care rate",
                "outcome_col": "anc",
                "multiplier": 100,
                "ylabel": "Antenatal care rate (%)",
                "plot_name": "antenatal_care_rate",
                "lower_is_better": False,
            },
            {
                "summary_name": "Normal referral",
                "outcome_col": "self_referral",
                "multiplier": 100,
                "ylabel": "Normal referral (%)",
                "plot_name": "normal_referral",
                "lower_is_better": False,
            },
        ],
        "location_distribution_plots": [
            {
                "rate_col": "initial_l45",
                "plot_title": "Initial delivery at L4/5",
                "plot_name": "initial_delivery_l45_rate",
            },
            {
                "rate_col": "final_l45",
                "plot_title": "Final delivery at L4/5",
                "plot_name": "final_delivery_l45_rate",
            },
        ],
    },
    "fqa": {
        "intervention_name": intervention_name_from_metadata("fqa"),
        "outcomes_to_plot": BASE_OUTCOMES,
    },
    "pulse": {
        "intervention_name": intervention_name_from_metadata("pulse"),
        "outcomes_to_plot": BASE_OUTCOMES,
    },
    "referral": {
        "intervention_name": intervention_name_from_metadata("referral"),
        "outcomes_to_plot": BASE_OUTCOMES,
    },
    "blood": {
        "intervention_name": intervention_name_from_metadata("blood"),
        "outcomes_to_plot": BASE_OUTCOMES,
    },
    "combined": {
        "intervention_name": intervention_name_from_metadata("combined"),
        "outcomes_to_plot": BASE_OUTCOMES + [
            {
                "summary_name": "Antenatal care rate",
                "outcome_col": "anc",
                "multiplier": 100,
                "ylabel": "Antenatal care rate (%)",
                "plot_name": "antenatal_care_rate",
                "lower_is_better": False,
            },
            {
                "summary_name": "Normal referral",
                "outcome_col": "self_referral",
                "multiplier": 100,
                "ylabel": "Normal referral (%)",
                "plot_name": "normal_referral",
                "lower_is_better": False,
            },
        ],
        "location_distribution_plots": [
            {
                "rate_col": "initial_l45",
                "plot_title": "Initial delivery at L4/5",
                "plot_name": "initial_delivery_l45_rate",
            },
            {
                "rate_col": "final_l45",
                "plot_title": "Final delivery at L4/5",
                "plot_name": "final_delivery_l45_rate",
            },
        ],
    },
}

PCT_CHANGE_EXCLUDE_INTERVENTIONS = {
    "Maternal complications": [
        INTERVENTION_CONFIGS["referral"]["intervention_name"],
        INTERVENTION_CONFIGS["blood"]["intervention_name"],
    ],
}

run_df = pd.concat(
    [
        pd.read_csv(resolve_county_csv(county_dir, "scenario_run_results.csv")).assign(County=county)
        for county, county_dir in COUNTY_DIRS.items()
    ],
    ignore_index=True,
)
run_df.columns = run_df.columns.str.strip()
run_df = run_df[run_df["run"] >= MIN_INCLUDED_RUN].copy()

location_df = pd.concat(
    [
        pd.read_csv(resolve_county_csv(county_dir, "scenario_location_run_results.csv")).assign(County=county)
        for county, county_dir in COUNTY_DIRS.items()
    ],
    ignore_index=True,
)
location_df.columns = location_df.columns.str.strip()
location_df = location_df[location_df["run"] >= MIN_INCLUDED_RUN].copy()

print(f"Using runs {MIN_INCLUDED_RUN}+ after excluding the first {EXCLUDE_FIRST_N_RUNS} runs")
print(f"Loaded run-level rows: {len(run_df):,}")
print(f"Loaded location-level rows: {len(location_df):,}")
print(f"Counties: {COUNTIES}")
print(f"Scenarios per county: {run_df.groupby('County')['scenario'].nunique().to_dict()}")

Using runs 1+ after excluding the first 0 runs
Loaded run-level rows: 23,200
Loaded location-level rows: 92,800
Counties: ['Kakamega', 'Kisii', 'Mombasa', 'Makueni']
Scenarios per county: {'Kakamega': 29, 'Kisii': 29, 'Makueni': 29, 'Mombasa': 29}

In [6]:
# =========================================================
# STYLE
# =========================================================

SDR_COLORS = {
    "paper": "#F6F3ED",
    "paper_deep": "#EDE7DA",
    "card": "#FFFFFF",
    "ink": "#1C1A15",
    "ink_soft": "#4A4339",
    "ink_muted": "#7E7464",
    "border": "#E2DAC8",
    "accent": "#B5471F",
    "baseline": "#9C9082",
    "current": "#C4511E",
    "moderate": "#D4A056",
    "high": "#2E5F5C",
}

COUNTY_COLORS = {
    "Kakamega": "#2E5F5C",
    "Kisii": "#5C6BC0",
    "Mombasa": "#C4511E",
    "Makueni": "#1B6B8A",
}

SCENARIO_COLORS = {
    "Baseline": SDR_COLORS["baseline"],
    "Current": SDR_COLORS["current"],
    "Moderate": SDR_COLORS["moderate"],
    "High": SDR_COLORS["high"],
}

plt.rcParams.update({
    "figure.facecolor": SDR_COLORS["paper"],
    "axes.facecolor": SDR_COLORS["card"],
    "axes.edgecolor": SDR_COLORS["border"],
    "axes.labelcolor": SDR_COLORS["ink_soft"],
    "xtick.color": SDR_COLORS["ink_muted"],
    "ytick.color": SDR_COLORS["ink_muted"],
    "text.color": SDR_COLORS["ink"],
    "font.family": "sans-serif",
    "legend.frameon": False,
    "grid.color": SDR_COLORS["border"],
    "grid.linestyle": "--",
    "grid.linewidth": 0.7,
})


def _save_plot(fig, plot_dir, file_prefix, plot_name, timestamp):
    plot_dir.mkdir(parents=True, exist_ok=True)
    save_path = plot_dir / f"{file_prefix}_{plot_name}_{timestamp}.png"
    fig.savefig(
        save_path,
        dpi=300,
        bbox_inches="tight",
        facecolor=SDR_COLORS["paper"],
    )
    plt.show()
    print(f"Saved plot to: {save_path}")


def _style_axes(ax):
    ax.grid(axis="y", alpha=0.55)
    ax.grid(axis="x", visible=False)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color(SDR_COLORS["border"])
    ax.spines["bottom"].set_color(SDR_COLORS["ink_muted"])
    ax.tick_params(axis="both", colors="black")


def _annotate_bars(ax, bars, values):
    for bar, value in zip(bars, values):
        if pd.notna(value):
            label = f"{value:,.0f}" if abs(value) >= 10 else f"{value:.1f}"
            ax.annotate(
                label,
                xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
                xytext=(0, 4),
                textcoords="offset points",
                ha="center",
                va="bottom",
                fontsize=7.5,
                color=SDR_COLORS["ink"],
                clip_on=False,
                zorder=5,
                bbox=dict(
                    facecolor="white",
                    edgecolor="none",
                    boxstyle="round,pad=0.12",
                    alpha=0.75,
                ),
            )


def available_scenario_labels(df, county=None, county_col="County", scenario_col="Scenario Label"):
    """Return scenario labels present in the generated data, preserving standard order."""
    if df is None or len(df) == 0 or scenario_col not in df.columns:
        return list(SCENARIOS)
    subset = df
    if county is not None and county_col in subset.columns:
        subset = subset[subset[county_col] == county]
    present = set(subset[scenario_col].dropna())
    labels = [label for label in SCENARIOS if label in present]
    return labels or list(SCENARIOS)


def scenarios_for_county(county, df=None):
    """Scenario labels available for this county in the generated data."""
    return available_scenario_labels(df, county=county)


def drop_unavailable_current(df, county_col="County", scenario_col="Scenario Label"):
    """Keep rows exactly as generated; missing levels are handled as NaN during plotting."""
    return df.copy() if df is not None else df


def get_standard_scenarios(prefix):
    return [f"{prefix}_{level}" for level in STANDARD_LEVELS]


def load_intervention_run_data(file_key, intervention_name):
    prefix = SCENARIO_PREFIX[file_key]
    subset = run_df[run_df["scenario"].str.startswith(f"{prefix}_")].copy()
    subset = subset[subset["level"].isin(STANDARD_LEVELS)].copy()

    if subset.empty:
        raise ValueError(f"No rows found for intervention '{intervention_name}'")

    subset["Scenario Label"] = subset["level"].map(LEVEL_TO_LABEL)
    subset["Intervention"] = subset["intervention"] if "intervention" in subset.columns else intervention_name
    subset["Run"] = subset["run"]
    return subset


def load_intervention_location_data(file_key, intervention_name):
    prefix = SCENARIO_PREFIX[file_key]
    subset = location_df[location_df["scenario"].str.startswith(f"{prefix}_")].copy()
    subset = subset[subset["level"].isin(STANDARD_LEVELS)].copy()

    if subset.empty:
        raise ValueError(f"No location rows found for intervention '{intervention_name}'")

    subset["Scenario Label"] = subset["level"].map(LEVEL_TO_LABEL)
    subset["Intervention"] = subset["intervention"] if "intervention" in subset.columns else intervention_name
    subset["Run"] = subset["run"]

    if "location" in subset.columns:
        subset["Delivery Location"] = subset["location"].astype(str).str.strip()
    else:
        raise ValueError("location column missing from scenario_location_run_results.csv")

    return subset


def summarize_preaggregated_outcome(df, outcome_col, multiplier, outcome_name, group_cols):
    if outcome_col not in df.columns:
        raise ValueError(f"Column not found for outcome: {outcome_col}")

    run_summary = df.copy()
    run_summary["value"] = run_summary[outcome_col] * multiplier

    summary = (
        run_summary.groupby(group_cols, observed=True)
        .agg(
            mean=("value", "mean"),
            sd=("value", "std"),
            n_runs=("Run", "nunique"),
        )
        .reset_index()
    )

    summary["ci95"] = 1.96 * summary["sd"] / np.sqrt(summary["n_runs"])
    summary["lower"] = summary["mean"] - summary["ci95"]
    summary["upper"] = summary["mean"] + summary["ci95"]
    summary["Outcome"] = outcome_name
    return summary


def make_change_table(summary_df, baseline_label="Baseline"):
    tables = []
    for county in COUNTIES:
        county_df = summary_df[summary_df["County"] == county].copy()
        baseline_rows = county_df.loc[county_df["Scenario Label"] == baseline_label, "mean"]
        if baseline_rows.empty:
            continue
        baseline_mean = baseline_rows.iloc[0]
        table = county_df.copy()
        table["Absolute Change vs Baseline"] = table["mean"] - baseline_mean
        table["Percent Change vs Baseline"] = (
            table["Absolute Change vs Baseline"] / baseline_mean * 100
        )
        table = table[table["Scenario Label"] != baseline_label].copy()
        tables.append(table)

    if not tables:
        return pd.DataFrame()

    out = pd.concat(tables, ignore_index=True)[
        [
            "County",
            "Intervention",
            "Scenario Label",
            "Outcome",
            "mean",
            "upper",
            "lower",
            "Absolute Change vs Baseline",
            "Percent Change vs Baseline",
        ]
    ].round(2)
    return drop_unavailable_current(out)


def plot_outcome_by_county(summary_df, outcome_name, ylabel, plot_name, intervention_name, file_prefix, plot_dir, timestamp, x_axis="scenario"):
    plot_df = summary_df[summary_df["Outcome"] == outcome_name].copy()

    fig, ax = plt.subplots(figsize=(13.5, 6.4))
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    ax.set_facecolor(SDR_COLORS["card"])

    if x_axis == "county":
        # Counties on x-axis; scenarios in legend
        x = np.arange(len(COUNTIES))
        width = 0.18
        offsets = np.linspace(-(len(SCENARIOS) - 1) / 2, (len(SCENARIOS) - 1) / 2, len(SCENARIOS))

        for i, scenario in enumerate(SCENARIOS):
            scenario_df = (
                plot_df[plot_df["Scenario Label"] == scenario]
                .set_index("County")
                .reindex(COUNTIES)
            )
            xpos = x + offsets[i] * width
            bars = ax.bar(
                xpos,
                scenario_df["mean"],
                width,
                yerr=scenario_df["ci95"],
                capsize=2,
                label=scenario,
                color=SCENARIO_COLORS[scenario],
                edgecolor="none",
                alpha=0.95,
                error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
            )
            _annotate_bars(ax, bars, scenario_df["mean"])

        ax.set_xlabel("County", fontsize=11)
        ax.set_xticks(x)
        ax.set_xticklabels(COUNTIES, fontsize=10)
        ax.legend(loc="upper right", fontsize=9, ncol=2, title="Scenario")
    else:
        # Scenarios on x-axis; counties in legend (default)
        x = np.arange(len(SCENARIOS))
        width = 0.18
        offsets = np.linspace(-(len(COUNTIES) - 1) / 2, (len(COUNTIES) - 1) / 2, len(COUNTIES))

        for i, county in enumerate(COUNTIES):
            county_df = (
                plot_df[plot_df["County"] == county]
                .set_index("Scenario Label")
                .reindex(SCENARIOS)
            )
            xpos = x + offsets[i] * width
            bars = ax.bar(
                xpos,
                county_df["mean"],
                width,
                yerr=county_df["ci95"],
                capsize=2,
                label=county,
                color=COUNTY_COLORS[county],
                edgecolor="none",
                alpha=0.95,
                error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
            )
            _annotate_bars(ax, bars, county_df["mean"])

        ax.set_xlabel("Scenario", fontsize=11)
        ax.set_xticks(x)
        ax.set_xticklabels(SCENARIOS, fontsize=10)
        ax.legend(loc="upper right", fontsize=9, ncol=2)

    ax.set_title(
        f"{intervention_name}: {outcome_name} — county comparison",
        fontsize=18,
        pad=16,
        color=SDR_COLORS["ink"],
    )
    ax.set_ylabel(ylabel, fontsize=11)
    _style_axes(ax)
    ax.margins(y=0.22)
    plt.tight_layout()
    _save_plot(fig, plot_dir, file_prefix, plot_name, timestamp)


def plot_outcome_by_location(summary_df, outcome_name, ylabel, plot_name, intervention_name, county, file_prefix, plot_dir, timestamp):
    plot_df = summary_df[
        (summary_df["Outcome"] == outcome_name) & (summary_df["County"] == county)
    ].copy()

    location_order = ["Home", "L2/3", "L4", "L5"]
    locations = [loc for loc in location_order if loc in plot_df["Delivery Location"].unique()]
    scenarios = scenarios_for_county(county, plot_df)

    fig, ax = plt.subplots(figsize=(12.5, 6.2))
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    ax.set_facecolor(SDR_COLORS["card"])

    x = np.arange(len(locations))
    width = 0.18
    offsets = np.linspace(-(len(scenarios) - 1) / 2, (len(scenarios) - 1) / 2, len(scenarios))

    for i, scenario in enumerate(scenarios):
        scenario_df = (
            plot_df[plot_df["Scenario Label"] == scenario]
            .set_index("Delivery Location")
            .reindex(locations)
        )
        xpos = x + offsets[i] * width
        bars = ax.bar(
            xpos,
            scenario_df["mean"],
            width,
            yerr=scenario_df["ci95"],
            capsize=2,
            label=scenario,
            color=SCENARIO_COLORS[scenario],
            edgecolor="none",
            alpha=0.95,
            error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
        )
        _annotate_bars(ax, bars, scenario_df["mean"])

    ax.set_title(
        f"{intervention_name}: {outcome_name} — {county}",
        fontsize=18,
        pad=16,
        color=SDR_COLORS["ink"],
    )
    ax.set_ylabel(ylabel, fontsize=11)
    ax.set_xlabel("Delivery location", fontsize=11)
    ax.set_xticks(x)
    ax.set_xticklabels(locations, fontsize=10.5)
    ax.legend(loc="upper right", fontsize=9)
    _style_axes(ax)
    ax.margins(y=0.22)
    plt.tight_layout()
    _save_plot(fig, plot_dir / county.lower(), file_prefix, plot_name, timestamp)


def plot_outcome_single_county(summary_df, outcome_name, ylabel, plot_name, intervention_name, county, file_prefix, plot_dir, timestamp):
    plot_df_source = summary_df[
        (summary_df["Outcome"] == outcome_name) & (summary_df["County"] == county)
    ].copy()
    scenarios = scenarios_for_county(county, plot_df_source)
    plot_df = (
        plot_df_source
        .set_index("Scenario Label")
        .reindex(scenarios)
    )

    fig, ax = plt.subplots(figsize=(9.0, 6.0))
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    ax.set_facecolor(SDR_COLORS["card"])

    x = np.arange(len(scenarios))
    colors = [SCENARIO_COLORS[s] for s in scenarios]

    bars = ax.bar(
        x,
        plot_df["mean"],
        width=0.62,
        yerr=plot_df["ci95"],
        capsize=3,
        color=colors,
        edgecolor="none",
        alpha=0.95,
        error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
    )
    _annotate_bars(ax, bars, plot_df["mean"])

    ax.set_title(
        f"{intervention_name}: {outcome_name} — {county}",
        fontsize=18,
        pad=16,
        color=SDR_COLORS["ink"],
    )
    ax.set_ylabel(ylabel, fontsize=11)
    ax.set_xlabel("Scenario", fontsize=11)
    ax.set_xticks(x)
    ax.set_xticklabels(scenarios, fontsize=10.5)
    _style_axes(ax)
    ax.margins(y=0.22)
    plt.tight_layout()
    _save_plot(fig, plot_dir / county.lower(), file_prefix, plot_name, timestamp)


def plot_l45_by_county(summary_df, plot_title, plot_name, intervention_name, file_prefix, plot_dir, timestamp, x_axis="scenario"):
    plot_df = summary_df[summary_df["Outcome"] == plot_title].copy()

    fig, ax = plt.subplots(figsize=(13.0, 5.8))
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    ax.set_facecolor(SDR_COLORS["card"])

    if x_axis == "county":
        x = np.arange(len(COUNTIES))
        width = 0.18
        offsets = np.linspace(-(len(SCENARIOS) - 1) / 2, (len(SCENARIOS) - 1) / 2, len(SCENARIOS))

        for i, scenario in enumerate(SCENARIOS):
            scenario_df = (
                plot_df[plot_df["Scenario Label"] == scenario]
                .set_index("County")
                .reindex(COUNTIES)
            )
            xpos = x + offsets[i] * width
            bars = ax.bar(
                xpos,
                scenario_df["mean"],
                width,
                yerr=scenario_df["ci95"],
                capsize=2,
                label=scenario,
                color=SCENARIO_COLORS[scenario],
                edgecolor="none",
                alpha=0.95,
                error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
            )
            for bar, value in zip(bars, scenario_df["mean"]):
                if pd.notna(value):
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + (scenario_df["ci95"].max() or 0) * 0.05,
                        f"{value:.0f}%",
                        ha="center",
                        va="bottom",
                        fontsize=7.5,
                        color=SDR_COLORS["ink"],
                    )

        ax.set_xlabel("County", fontsize=11)
        ax.set_xticks(x)
        ax.set_xticklabels(COUNTIES, fontsize=10)
        ax.legend(loc="upper right", fontsize=9, ncol=2, title="Scenario")
    else:
        x = np.arange(len(SCENARIOS))
        width = 0.18
        offsets = np.linspace(-(len(COUNTIES) - 1) / 2, (len(COUNTIES) - 1) / 2, len(COUNTIES))

        for i, county in enumerate(COUNTIES):
            county_df = (
                plot_df[plot_df["County"] == county]
                .set_index("Scenario Label")
                .reindex(SCENARIOS)
            )
            xpos = x + offsets[i] * width
            bars = ax.bar(
                xpos,
                county_df["mean"],
                width,
                yerr=county_df["ci95"],
                capsize=2,
                label=county,
                color=COUNTY_COLORS[county],
                edgecolor="none",
                alpha=0.95,
                error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
            )
            for bar, value in zip(bars, county_df["mean"]):
                if pd.notna(value):
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + (county_df["ci95"].max() or 0) * 0.05,
                        f"{value:.0f}%",
                        ha="center",
                        va="bottom",
                        fontsize=7.5,
                        color=SDR_COLORS["ink"],
                    )

        ax.set_xlabel("Scenario", fontsize=11)
        ax.set_xticks(x)
        ax.set_xticklabels(SCENARIOS, fontsize=10)
        ax.legend(loc="upper right", fontsize=9, ncol=2)

    ax.set_title(
        f"{intervention_name}: {plot_title} — county comparison",
        fontsize=18,
        pad=16,
        color=SDR_COLORS["ink"],
    )
    ax.set_ylabel("Share of mothers (%)", fontsize=11)
    _style_axes(ax)
    ax.margins(y=0.22)
    plt.tight_layout()
    _save_plot(fig, plot_dir, file_prefix, plot_name, timestamp)

In [7]:
def build_pct_change_grid(outcome_spec, exclude_interventions=None):
    exclude_interventions = exclude_interventions or []
    rows = []

    for file_key, enabled in RUN_INTERVENTIONS.items():
        if not enabled:
            continue

        intervention_name = INTERVENTION_CONFIGS[file_key]["intervention_name"]
        if intervention_name in exclude_interventions:
            continue

        prefix = SCENARIO_PREFIX[file_key]
        subset = load_intervention_run_data(file_key, intervention_name)

        for county in COUNTIES:
            county_df = subset[subset["County"] == county]
            baseline = (
                county_df.loc[county_df["Scenario Label"] == "Baseline", outcome_spec["outcome_col"]]
                .mean()
                * outcome_spec["multiplier"]
            )

            for level in CHANGE_LEVELS:
                label = LEVEL_TO_LABEL[level]
                scenario_mean = (
                    county_df.loc[county_df["Scenario Label"] == label, outcome_spec["outcome_col"]]
                    .mean()
                    * outcome_spec["multiplier"]
                )
                pct_change = (scenario_mean - baseline) / baseline * 100 if baseline else np.nan
                rows.append({
                    "Intervention": intervention_name,
                    "County": county,
                    "Scenario Label": label,
                    "Percent change vs baseline": pct_change,
                })

    return pd.DataFrame(rows)


def plot_county_pct_change_subplots(outcome_spec, exclude_interventions=None):
    grid_df = build_pct_change_grid(outcome_spec, exclude_interventions=exclude_interventions)
    if grid_df.empty:
        print(f"No data for {outcome_spec['summary_name']} pct-change grid")
        return grid_df

    interventions = [
        INTERVENTION_CONFIGS[k]["intervention_name"]
        for k, enabled in RUN_INTERVENTIONS.items()
        if enabled and INTERVENTION_CONFIGS[k]["intervention_name"] not in (exclude_interventions or [])
    ]

    n_rows = len(interventions)
    n_cols = len(COUNTIES)

    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(3.0 * n_cols + 1.2, 2.2 * n_rows + 1.0),
        sharex=True,
    )
    fig.patch.set_facecolor(SDR_COLORS["paper"])

    if n_rows == 1:
        axes = np.array([axes])
    if n_cols == 1:
        axes = axes.reshape(-1, 1)

    bar_colors = [SCENARIO_COLORS[label] for label in CHANGE_LEVEL_LABELS]

    all_values = grid_df["Percent change vs baseline"].abs().max()
    y_limit = max(5, np.ceil(all_values / 5) * 5) if pd.notna(all_values) else 10

    for r, intervention in enumerate(interventions):
        for c, county in enumerate(COUNTIES):
            ax = axes[r, c]
            ax.set_facecolor(SDR_COLORS["card"])

            cell = (
                grid_df[
                    (grid_df["Intervention"] == intervention)
                    & (grid_df["County"] == county)
                ]
                .set_index("Scenario Label")
                .reindex(CHANGE_LEVEL_LABELS)
            )

            values = cell["Percent change vs baseline"].to_numpy(dtype=float)
            x = np.arange(len(CHANGE_LEVEL_LABELS))

            bars = ax.bar(
                x,
                values,
                color=bar_colors,
                width=0.62,
                edgecolor="none",
                alpha=0.95,
            )

            for bar, value in zip(bars, values):
                if pd.notna(value):
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + np.sign(value) * 0.8,
                        f"{value:.1f}%",
                        ha="center",
                        va="bottom" if value >= 0 else "top",
                        fontsize=8,
                        color=SDR_COLORS["ink"],
                    )

            ax.axhline(0, color=SDR_COLORS["ink_muted"], linewidth=0.8)
            ax.set_ylim(-y_limit, y_limit)
            ax.set_xticks(x)
            ax.set_xticklabels(CHANGE_LEVEL_LABELS, fontsize=8, rotation=35, ha="right")
            ax.grid(axis="y", alpha=0.4)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)

            if r == 0:
                ax.set_title(county, fontsize=11, color=SDR_COLORS["ink"], pad=8)
            if c == 0:
                ax.set_ylabel(intervention, fontsize=10, color=SDR_COLORS["ink_soft"])

    fig.suptitle(
        f"{outcome_spec['summary_name']}: percent change from baseline by county",
        fontsize=16,
        y=1.01,
        color=SDR_COLORS["ink"],
    )

    from matplotlib.patches import Patch
    legend_handles = [
        Patch(facecolor=SCENARIO_COLORS[label], edgecolor="none", label=label)
        for label in CHANGE_LEVEL_LABELS
    ]
    fig.legend(
        handles=legend_handles,
        loc="lower center",
        ncol=3,
        bbox_to_anchor=(0.5, -0.02),
        fontsize=10,
    )

    plt.tight_layout()

    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    summary_dir = PLOTS_ROOT / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    plot_name = f"{outcome_spec['plot_name']}_county_pct_change_subplots"
    png_path = summary_dir / f"{plot_name}_{timestamp}.png"
    csv_path = summary_dir / f"{plot_name}_{timestamp}.csv"

    # fig.savefig(png_path, dpi=300, bbox_inches="tight", facecolor=SDR_COLORS["paper"])
    grid_df.round(2).to_csv(csv_path, index=False)
    plt.show()
    # print(f"Saved pct-change subplots to: {png_path}")
    # print(f"Saved pct-change table to: {csv_path}")
    return grid_df


def _pct_change_diverging_cmap():
    from matplotlib.colors import LinearSegmentedColormap
    return LinearSegmentedColormap.from_list(
        "sdr_pct_div", [SDR_COLORS["accent"], "#FFFFFF", SDR_COLORS["high"]]
    )


def _draw_pct_change_heatmap(ax, matrix, goodness, row_labels, col_keys, max_abs, value_fmt="{:.1f}%"):
    from matplotlib.colors import TwoSlopeNorm

    n_rows = len(row_labels)
    n_cols = len(col_keys)
    scenarios_per_county = len(CHANGE_LEVEL_LABELS)

    cmap = _pct_change_diverging_cmap()
    norm = TwoSlopeNorm(vmin=-max_abs, vcenter=0.0, vmax=max_abs)

    im = ax.imshow(
        goodness,
        cmap=cmap,
        norm=norm,
        aspect="auto",
        interpolation="nearest",
    )

    for r in range(n_rows):
        for c in range(n_cols):
            value = matrix[r, c]
            if pd.notna(value):
                g_norm = goodness[r, c] / max_abs if max_abs else 0.0
                text_color = "white" if abs(g_norm) > 0.55 else SDR_COLORS["ink"]
                ax.text(
                    c, r, value_fmt.format(value),
                    ha="center", va="center",
                    fontsize=13, color=text_color,
                )

    ax.set_xticks(np.arange(n_cols))
    ax.set_xticklabels([scenario for (_, scenario) in col_keys], fontsize=11, color="black")
    ax.set_yticks(np.arange(n_rows))
    ax.set_yticklabels(row_labels, fontsize=13, color="black")
    ax.tick_params(axis="both", colors="black")

    counties_in_order = []
    for county, _ in col_keys:
        if county not in counties_in_order:
            counties_in_order.append(county)
    for i, county in enumerate(counties_in_order):
        center = i * scenarios_per_county + (scenarios_per_county - 1) / 2
        ax.text(
            center, -0.75, county,
            ha="center", va="bottom",
            fontsize=13, fontweight="bold", color="black",
        )
        if i > 0:
            ax.axvline(i * scenarios_per_county - 0.5, color=SDR_COLORS["paper"], linewidth=3)

    ax.set_xticks(np.arange(-0.5, n_cols, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, n_rows, 1), minor=True)
    ax.grid(which="minor", color=SDR_COLORS["paper"], linewidth=2, linestyle="-")
    ax.tick_params(which="minor", length=0)
    ax.tick_params(which="major", length=0)
    for spine in ax.spines.values():
        spine.set_visible(False)

    ax.set_ylim(n_rows - 0.5, -1.4)
    return im


def _add_pct_change_colorbar(fig, ax, im, max_abs, lower_is_better=True, mixed_direction=False):
    cbar = fig.colorbar(
        im,
        ax=ax,
        orientation="horizontal",
        fraction=0.05,
        pad=0.22,
        aspect=36,
        shrink=0.92,
    )
    ticks = np.linspace(-max_abs, max_abs, 5)
    cbar.set_ticks(ticks)
    cbar.set_ticklabels(["Worsening", "", "No change", "", "Improvement"])
    cbar.ax.tick_params(labelsize=11, color="black", labelcolor="black")
    cbar.outline.set_visible(False)
    return cbar


def _save_summary_heatmap(fig, grid_df, plot_name):
    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    summary_dir = PLOTS_ROOT / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    png_path = summary_dir / f"{plot_name}_{timestamp}.png"
    csv_path = summary_dir / f"{plot_name}_{timestamp}.csv"
    # fig.savefig(png_path, dpi=300, bbox_inches="tight", facecolor=SDR_COLORS["paper"])
    grid_df.round(2).to_csv(csv_path, index=False)
    plt.show()
    # print(f"Saved pct-change heatmap to: {png_path}")
    # print(f"Saved pct-change table to: {csv_path}")


def plot_county_pct_change_heatmap(outcome_spec, exclude_interventions=None):
    grid_df = build_pct_change_grid(outcome_spec, exclude_interventions=exclude_interventions)
    if grid_df.empty:
        print(f"No data for {outcome_spec['summary_name']} pct-change heatmap")
        return grid_df

    interventions = [
        INTERVENTION_CONFIGS[k]["intervention_name"]
        for k, enabled in RUN_INTERVENTIONS.items()
        if enabled and INTERVENTION_CONFIGS[k]["intervention_name"] not in (exclude_interventions or [])
    ]

    col_keys = [(county, scenario) for county in COUNTIES for scenario in CHANGE_LEVEL_LABELS]
    n_rows = len(interventions)
    n_cols = len(col_keys)

    matrix = np.full((n_rows, n_cols), np.nan)
    for r, intervention in enumerate(interventions):
        for c, (county, scenario) in enumerate(col_keys):
            sel = grid_df[
                (grid_df["Intervention"] == intervention)
                & (grid_df["County"] == county)
                & (grid_df["Scenario Label"] == scenario)
            ]["Percent change vs baseline"]
            if not sel.empty:
                matrix[r, c] = sel.iloc[0]

    lower_is_better = outcome_spec.get("lower_is_better", True)
    goodness = (-matrix if lower_is_better else matrix)

    finite = np.abs(matrix[np.isfinite(matrix)])
    max_abs = max(finite.max(), 1.0) if finite.size else 1.0

    fig, ax = plt.subplots(figsize=(1.25 * n_cols + 2.8, 1.05 * n_rows + 2.6))
    fig.patch.set_facecolor(SDR_COLORS["paper"])

    im = _draw_pct_change_heatmap(ax, matrix, goodness, interventions, col_keys, max_abs)

    ax.set_title(
        f"{outcome_spec['summary_name']}: % change from baseline",
        fontsize=17, pad=34, color=SDR_COLORS["ink"],
    )
    _add_pct_change_colorbar(fig, ax, im, max_abs, lower_is_better=lower_is_better)

    plt.tight_layout(rect=(0, 0.04, 1, 1))
    _save_summary_heatmap(fig, grid_df, f"{outcome_spec['plot_name']}_county_pct_change_heatmap")
    return grid_df


def plot_prompts_extra_pct_change_heatmap(outcome_specs, intervention_name="PROMPTS", plot_name="prompts_extras"):
    rows_data = []
    for spec in outcome_specs:
        grid = build_pct_change_grid(spec)
        grid = grid[grid["Intervention"] == intervention_name].copy()
        if grid.empty:
            continue
        grid["Outcome"] = spec["summary_name"]
        grid["lower_is_better"] = spec.get("lower_is_better", True)
        rows_data.append(grid)

    if not rows_data:
        print("No data for PROMPTS extras pct-change heatmap")
        return pd.DataFrame()

    grid_df = pd.concat(rows_data, ignore_index=True)
    outcome_names = [s["summary_name"] for s in outcome_specs if s["summary_name"] in grid_df["Outcome"].unique()]

    col_keys = [(county, scenario) for county in COUNTIES for scenario in CHANGE_LEVEL_LABELS]
    n_rows = len(outcome_names)
    n_cols = len(col_keys)

    matrix = np.full((n_rows, n_cols), np.nan)
    goodness = np.full((n_rows, n_cols), np.nan)
    for r, outcome_name in enumerate(outcome_names):
        lower_is_better = bool(grid_df.loc[grid_df["Outcome"] == outcome_name, "lower_is_better"].iloc[0])
        for c, (county, scenario) in enumerate(col_keys):
            sel = grid_df[
                (grid_df["Outcome"] == outcome_name)
                & (grid_df["County"] == county)
                & (grid_df["Scenario Label"] == scenario)
            ]["Percent change vs baseline"]
            if not sel.empty:
                value = sel.iloc[0]
                matrix[r, c] = value
                goodness[r, c] = -value if lower_is_better else value

    finite = np.abs(matrix[np.isfinite(matrix)])
    max_abs = max(finite.max(), 1.0) if finite.size else 1.0

    fig, ax = plt.subplots(figsize=(1.25 * n_cols + 2.8, 1.05 * n_rows + 2.6))
    fig.patch.set_facecolor(SDR_COLORS["paper"])

    im = _draw_pct_change_heatmap(ax, matrix, goodness, outcome_names, col_keys, max_abs)

    ax.set_title(
        f"{intervention_name}: % change from baseline",
        fontsize=17, pad=34, color=SDR_COLORS["ink"],
    )
    _add_pct_change_colorbar(fig, ax, im, max_abs, mixed_direction=True)

    plt.tight_layout(rect=(0, 0.04, 1, 1))
    _save_summary_heatmap(fig, grid_df, f"{plot_name}_pct_change_heatmap")
    return grid_df


def run_intervention_plots(file_key, config):
    intervention_name = config["intervention_name"]
    outcomes_to_plot = config["outcomes_to_plot"]

    run_subset = load_intervention_run_data(file_key, intervention_name)
    loc_subset = load_intervention_location_data(file_key, intervention_name)

    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    file_prefix = intervention_name.replace(" ", "_").lower()
    plot_dir = PLOTS_ROOT / "county_comparison" / file_prefix

    print(f"\nRunning plots for: {intervention_name}")
    change_tables = []

    for outcome in outcomes_to_plot:
        run_summary = summarize_preaggregated_outcome(
            run_subset,
            outcome_col=outcome["outcome_col"],
            multiplier=outcome["multiplier"],
            outcome_name=outcome["summary_name"],
            group_cols=["County", "Intervention", "Scenario Label"],
        )

        plot_outcome_by_county(
            run_summary,
            outcome_name=outcome["summary_name"],
            ylabel=outcome["ylabel"],
            plot_name=f"{outcome['plot_name']}_county_comparison",
            intervention_name=intervention_name,
            file_prefix=file_prefix,
            plot_dir=plot_dir,
            timestamp=timestamp,
            x_axis="county" if file_key == "combined" else "scenario",
        )

        if outcome["outcome_col"] in loc_subset.columns:
            loc_summary = summarize_preaggregated_outcome(
                loc_subset,
                outcome_col=outcome["outcome_col"],
                multiplier=outcome["multiplier"],
                outcome_name=outcome["summary_name"],
                group_cols=["County", "Intervention", "Scenario Label", "Delivery Location"],
            )

            for county in COUNTIES:
                plot_outcome_by_location(
                    loc_summary,
                    outcome_name=outcome["summary_name"],
                    ylabel=outcome["ylabel"],
                    plot_name=f"{outcome['plot_name']}_location",
                    intervention_name=intervention_name,
                    county=county,
                    file_prefix=file_prefix,
                    plot_dir=plot_dir,
                    timestamp=timestamp,
                )
        else:
            # No location-level data for this outcome (e.g. normal referral).
            # Make a per-county overall bar plot with the 4 scenario bars instead.
            for county in COUNTIES:
                plot_outcome_single_county(
                    run_summary,
                    outcome_name=outcome["summary_name"],
                    ylabel=outcome["ylabel"],
                    plot_name=f"{outcome['plot_name']}_overall_by_county",
                    intervention_name=intervention_name,
                    county=county,
                    file_prefix=file_prefix,
                    plot_dir=plot_dir,
                    timestamp=timestamp,
                )

        change_tables.append(make_change_table(run_summary))

    for loc_plot in config.get("location_distribution_plots", []):
        l45_summary = summarize_preaggregated_outcome(
            run_subset,
            outcome_col=loc_plot["rate_col"],
            multiplier=100,
            outcome_name=loc_plot["plot_title"],
            group_cols=["County", "Intervention", "Scenario Label"],
        )
        plot_l45_by_county(
            l45_summary,
            plot_title=loc_plot["plot_title"],
            plot_name=loc_plot["plot_name"],
            intervention_name=intervention_name,
            file_prefix=file_prefix,
            plot_dir=plot_dir,
            timestamp=timestamp,
            x_axis="county" if file_key == "combined" else "scenario",
        )

        for county in COUNTIES:
            plot_outcome_single_county(
                l45_summary,
                outcome_name=loc_plot["plot_title"],
                ylabel="Share of mothers (%)",
                plot_name=f"{loc_plot['plot_name']}_overall_by_county",
                intervention_name=intervention_name,
                county=county,
                file_prefix=file_prefix,
                plot_dir=plot_dir,
                timestamp=timestamp,
            )

        change_tables.append(make_change_table(l45_summary))

    if change_tables:
        summary_table = pd.concat(change_tables, ignore_index=True)
        table_path = plot_dir / f"{file_prefix}_summary_change_table_{timestamp}.csv"
        # summary_table.to_csv(table_path, index=False)
        # print(f"Saved summary table to: {table_path}")
        display(summary_table)

In [8]:
# =========================================================
# RUN INTERVENTION PLOTS
# =========================================================

for file_key, should_run in RUN_INTERVENTIONS.items():
    if should_run:
        run_intervention_plots(file_key, INTERVENTION_CONFIGS[file_key])

Running plots for: MENTORS
Saved plot to: county_comparison/mentors/mentors_maternal_mortality_ratio_county_comparison_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/mentors/kakamega/mentors_maternal_mortality_ratio_location_20260813_1450.png
Saved plot to: county_comparison/mentors/kisii/mentors_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/mentors/mombasa/mentors_maternal_mortality_ratio_location_20260813_1450.png
Saved plot to: county_comparison/mentors/makueni/mentors_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/mentors/mentors_maternal_complications_county_comparison_20260813_1450.png
Saved plot to: county_comparison/mentors/kakamega/mentors_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/mentors/kisii/mentors_maternal_complications_location_20260813_1450.png
Saved plot to: county_comparison/mentors/mombasa/mentors_maternal_complications_location_20260813_1450.png
Saved plot to: county_comparison/mentors/makueni/mentors_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,MENTORS,Current,Maternal mortality ratio,221.46,232.14,210.78,-7.83,-3.41
1,Kakamega,MENTORS,High,Maternal mortality ratio,212.56,222.83,202.29,-16.72,-7.29
2,Kakamega,MENTORS,Moderate,Maternal mortality ratio,216.71,227.17,206.26,-12.57,-5.48
3,Kisii,MENTORS,Current,Maternal mortality ratio,59.41,62.25,56.57,-6.41,-9.74
4,Kisii,MENTORS,High,Maternal mortality ratio,54.82,57.40,52.24,-11.00,-16.71
5,Kisii,MENTORS,Moderate,Maternal mortality ratio,57.23,59.94,54.51,-8.60,-13.06
6,Mombasa,MENTORS,Current,Maternal mortality ratio,55.46,57.79,53.13,-4.35,-7.27
7,Mombasa,MENTORS,High,Maternal mortality ratio,51.34,53.48,49.21,-8.46,-14.15
8,Mombasa,MENTORS,Moderate,Maternal mortality ratio,53.33,55.56,51.10,-6.47,-10.82
9,Makueni,MENTORS,Current,Maternal mortality ratio,124.67,130.03,119.31,-13.41,-9.71
10,Makueni,MENTORS,High,Maternal mortality ratio,115.60,120.67,110.54,-22.47,-16.28
11,Makueni,MENTORS,Moderate,Maternal mortality ratio,120.42,125.64,115.20,-17.66,-12.79
12,Kakamega,MENTORS,Current,Maternal complications,2.90,3.05,2.74,-0.22,-6.94
13,Kakamega,MENTORS,High,Maternal complications,2.62,2.76,2.48,-0.49,-15.89
14,Kakamega,MENTORS,Moderate,Maternal complications,2.75,2.90,2.60,-0.37,-11.73
15,Kisii,MENTORS,Current,Maternal complications,3.46,3.64,3.28,-0.63,-15.45
16,Kisii,MENTORS,High,Maternal complications,3.02,3.19,2.86,-1.07,-26.13
17,Kisii,MENTORS,Moderate,Maternal complications,3.24,3.42,3.07,-0.85,-20.73
18,Mombasa,MENTORS,Current,Maternal complications,4.25,4.47,4.04,-0.65,-13.31
19,Mombasa,MENTORS,High,Maternal complications,3.77,3.97,3.57,-1.14,-23.21
20,Mombasa,MENTORS,Moderate,Maternal complications,4.01,4.21,3.80,-0.90,-18.34
21,Makueni,MENTORS,Current,Maternal complications,3.92,4.10,3.74,-0.79,-16.74
22,Makueni,MENTORS,High,Maternal complications,3.40,3.56,3.24,-1.31,-27.83
23,Makueni,MENTORS,Moderate,Maternal complications,3.67,3.85,3.50,-1.04,-22.00

Running plots for: PROMPTS
Saved plot to: county_comparison/prompts/prompts_maternal_mortality_ratio_county_comparison_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/kakamega/prompts_maternal_mortality_ratio_location_20260813_1450.png
Saved plot to: county_comparison/prompts/kisii/prompts_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/mombasa/prompts_maternal_mortality_ratio_location_20260813_1450.png
Saved plot to: county_comparison/prompts/makueni/prompts_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/prompts_maternal_complications_county_comparison_20260813_1450.png
Saved plot to: county_comparison/prompts/kakamega/prompts_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/kisii/prompts_maternal_complications_location_20260813_1450.png
Saved plot to: county_comparison/prompts/mombasa/prompts_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:220: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, ax = plt.subplots(figsize=(13.5, 6.4))

Saved plot to: county_comparison/prompts/makueni/prompts_maternal_complications_location_20260813_1450.png
Saved plot to: county_comparison/prompts/prompts_antenatal_care_rate_county_comparison_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/kakamega/prompts_antenatal_care_rate_location_20260813_1450.png
Saved plot to: county_comparison/prompts/kisii/prompts_antenatal_care_rate_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/mombasa/prompts_antenatal_care_rate_location_20260813_1450.png
Saved plot to: county_comparison/prompts/makueni/prompts_antenatal_care_rate_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/prompts_normal_referral_county_comparison_20260813_1450.png
Saved plot to: county_comparison/prompts/kakamega/prompts_normal_referral_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/kisii/prompts_normal_referral_overall_by_county_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/mombasa/prompts_normal_referral_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/makueni/prompts_normal_referral_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/prompts_initial_delivery_l45_rate_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/kakamega/prompts_initial_delivery_l45_rate_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/kisii/prompts_initial_delivery_l45_rate_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/mombasa/prompts_initial_delivery_l45_rate_overall_by_county_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/makueni/prompts_initial_delivery_l45_rate_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/prompts_final_delivery_l45_rate_20260813_1450.png
Saved plot to: county_comparison/prompts/kakamega/prompts_final_delivery_l45_rate_overall_by_county_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/prompts/kisii/prompts_final_delivery_l45_rate_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/mombasa/prompts_final_delivery_l45_rate_overall_by_county_20260813_1450.png
Saved plot to: county_comparison/prompts/makueni/prompts_final_delivery_l45_rate_overall_by_county_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,PROMPTS,Current,Maternal mortality ratio,229.29,240.31,218.26,0.00,0.00
1,Kakamega,PROMPTS,High,Maternal mortality ratio,167.25,175.17,159.34,-62.03,-27.05
2,Kakamega,PROMPTS,Moderate,Maternal mortality ratio,211.10,220.93,201.26,-18.19,-7.93
3,Kisii,PROMPTS,Current,Maternal mortality ratio,65.50,68.62,62.37,-0.33,-0.50
4,Kisii,PROMPTS,High,Maternal mortality ratio,38.97,40.78,37.15,-26.86,-40.80
...,...,...,...,...,...,...,...,...,...
67,Mombasa,PROMPTS,High,Final delivery at L4/5,71.62,71.65,71.60,2.26,3.26
68,Mombasa,PROMPTS,Moderate,Final delivery at L4/5,70.29,70.31,70.27,0.93,1.34
69,Makueni,PROMPTS,Current,Final delivery at L4/5,65.95,65.98,65.92,0.24,0.36
70,Makueni,PROMPTS,High,Final delivery at L4/5,72.50,72.50,72.50,6.79,10.33
71,Makueni,PROMPTS,Moderate,Final delivery at L4/5,70.22,70.24,70.19,4.51,6.86

Running plots for: FQA

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/fqa_maternal_mortality_ratio_county_comparison_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/kakamega/fqa_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/kisii/fqa_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/mombasa/fqa_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/makueni/fqa_maternal_mortality_ratio_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/fqa_maternal_complications_county_comparison_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/kakamega/fqa_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/kisii/fqa_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/fqa/mombasa/fqa_maternal_complications_location_20260813_1450.png
Saved plot to: county_comparison/fqa/makueni/fqa_maternal_complications_location_20260813_1450.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,FQA,Current,Maternal mortality ratio,221.46,232.14,210.78,0.00,0.00
1,Kakamega,FQA,High,Maternal mortality ratio,220.86,231.52,210.21,-0.60,-0.27
2,Kakamega,FQA,Moderate,Maternal mortality ratio,221.16,231.84,210.49,-0.30,-0.13
3,Kisii,FQA,Current,Maternal mortality ratio,58.75,61.43,56.08,0.00,0.00
4,Kisii,FQA,High,Maternal mortality ratio,59.49,62.29,56.70,0.74,1.26
5,Kisii,FQA,Moderate,Maternal mortality ratio,58.82,61.54,56.11,0.07,0.11
6,Mombasa,FQA,Current,Maternal mortality ratio,55.75,58.09,53.41,0.00,0.00
7,Mombasa,FQA,High,Maternal mortality ratio,55.51,57.84,53.19,-0.23,-0.42
8,Mombasa,FQA,Moderate,Maternal mortality ratio,55.61,57.94,53.28,-0.14,-0.25
9,Makueni,FQA,Current,Maternal mortality ratio,125.66,131.05,120.26,-0.04,-0.03
10,Makueni,FQA,High,Maternal mortality ratio,124.77,130.13,119.42,-0.93,-0.74
11,Makueni,FQA,Moderate,Maternal mortality ratio,125.23,130.60,119.85,-0.48,-0.38
12,Kakamega,FQA,Current,Maternal complications,2.90,3.05,2.74,0.00,0.00
13,Kakamega,FQA,High,Maternal complications,2.87,3.03,2.72,-0.02,-0.80
14,Kakamega,FQA,Moderate,Maternal complications,2.89,3.04,2.73,-0.01,-0.42
15,Kisii,FQA,Current,Maternal complications,3.52,3.70,3.34,-0.00,-0.02
16,Kisii,FQA,High,Maternal complications,3.44,3.62,3.27,-0.08,-2.23
17,Kisii,FQA,Moderate,Maternal complications,3.49,3.67,3.31,-0.03,-0.91
18,Mombasa,FQA,Current,Maternal complications,4.29,4.50,4.07,-0.00,-0.01
19,Mombasa,FQA,High,Maternal complications,4.24,4.46,4.03,-0.04,-0.99
20,Mombasa,FQA,Moderate,Maternal complications,4.26,4.48,4.05,-0.02,-0.52
21,Makueni,FQA,Current,Maternal complications,3.99,4.17,3.81,-0.00,-0.05
22,Makueni,FQA,High,Maternal complications,3.93,4.11,3.75,-0.06,-1.55
23,Makueni,FQA,Moderate,Maternal complications,3.96,4.14,3.78,-0.03,-0.81

Running plots for: PULSE

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/pulse/pulse_maternal_mortality_ratio_county_comparison_20260813_1451.png
Saved plot to: county_comparison/pulse/kakamega/pulse_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/pulse/kisii/pulse_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/pulse/mombasa/pulse_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/pulse/makueni/pulse_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/pulse/pulse_maternal_complications_county_comparison_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/pulse/kakamega/pulse_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/pulse/kisii/pulse_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/pulse/mombasa/pulse_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/pulse/makueni/pulse_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,PULSE,Current,Maternal mortality ratio,229.29,240.31,218.26,0.00,0.00
1,Kakamega,PULSE,High,Maternal mortality ratio,223.62,234.47,212.76,-5.67,-2.47
2,Kakamega,PULSE,Moderate,Maternal mortality ratio,226.93,237.77,216.08,-2.36,-1.03
3,Kisii,PULSE,Current,Maternal mortality ratio,64.73,67.73,61.72,-1.10,-1.67
4,Kisii,PULSE,High,Maternal mortality ratio,63.76,66.77,60.74,-2.07,-3.14
5,Kisii,PULSE,Moderate,Maternal mortality ratio,64.02,67.13,60.90,-1.81,-2.74
6,Mombasa,PULSE,Current,Maternal mortality ratio,59.80,62.34,57.27,0.00,0.00
7,Mombasa,PULSE,High,Maternal mortality ratio,58.79,61.37,56.20,-1.02,-1.70
8,Mombasa,PULSE,Moderate,Maternal mortality ratio,59.42,62.00,56.84,-0.39,-0.65
9,Makueni,PULSE,Current,Maternal mortality ratio,138.08,143.86,132.30,0.00,0.00
10,Makueni,PULSE,High,Maternal mortality ratio,133.99,139.59,128.38,-4.09,-2.96
11,Makueni,PULSE,Moderate,Maternal mortality ratio,135.43,141.22,129.64,-2.65,-1.92
12,Kakamega,PULSE,Current,Maternal complications,3.11,3.27,2.95,0.00,0.00
13,Kakamega,PULSE,High,Maternal complications,2.96,3.11,2.80,-0.16,-5.05
14,Kakamega,PULSE,Moderate,Maternal complications,3.03,3.19,2.87,-0.08,-2.61
15,Kisii,PULSE,Current,Maternal complications,4.09,4.29,3.89,-0.00,-0.01
16,Kisii,PULSE,High,Maternal complications,3.86,4.05,3.67,-0.23,-5.69
17,Kisii,PULSE,Moderate,Maternal complications,3.97,4.17,3.77,-0.12,-2.97
18,Mombasa,PULSE,Current,Maternal complications,4.91,5.14,4.67,0.00,0.00
19,Mombasa,PULSE,High,Maternal complications,4.82,5.05,4.59,-0.08,-1.71
20,Mombasa,PULSE,Moderate,Maternal complications,4.87,5.10,4.64,-0.04,-0.75
21,Makueni,PULSE,Current,Maternal complications,4.71,4.91,4.51,0.00,0.00
22,Makueni,PULSE,High,Maternal complications,4.44,4.63,4.24,-0.27,-5.79
23,Makueni,PULSE,Moderate,Maternal complications,4.58,4.78,4.38,-0.13,-2.83

Running plots for: Transfer & EMT
Saved plot to: county_comparison/transfer_&_emt/transfer_&_emt_maternal_mortality_ratio_county_comparison_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/transfer_&_emt/kakamega/transfer_&_emt_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/transfer_&_emt/kisii/transfer_&_emt_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/transfer_&_emt/mombasa/transfer_&_emt_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/transfer_&_emt/makueni/transfer_&_emt_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/transfer_&_emt/transfer_&_emt_maternal_complications_county_comparison_20260813_1451.png
Saved plot to: county_comparison/transfer_&_emt/kakamega/transfer_&_emt_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/transfer_&_emt/kisii/transfer_&_emt_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/transfer_&_emt/mombasa/transfer_&_emt_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/transfer_&_emt/makueni/transfer_&_emt_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,Transfer & EMT,Current,Maternal mortality ratio,229.29,240.31,218.26,0.00,0.00
1,Kakamega,Transfer & EMT,High,Maternal mortality ratio,227.13,238.07,216.18,-2.16,-0.94
2,Kakamega,Transfer & EMT,Moderate,Maternal mortality ratio,228.17,239.17,217.18,-1.11,-0.49
3,Kisii,Transfer & EMT,Current,Maternal mortality ratio,65.82,68.97,62.67,0.00,0.00
4,Kisii,Transfer & EMT,High,Maternal mortality ratio,63.66,66.71,60.62,-2.16,-3.28
5,Kisii,Transfer & EMT,Moderate,Maternal mortality ratio,64.66,67.75,61.57,-1.16,-1.77
6,Mombasa,Transfer & EMT,Current,Maternal mortality ratio,59.71,62.24,57.17,-0.10,-0.16
7,Mombasa,Transfer & EMT,High,Maternal mortality ratio,59.18,61.69,56.67,-0.62,-1.04
8,Mombasa,Transfer & EMT,Moderate,Maternal mortality ratio,59.50,62.02,56.98,-0.30,-0.50
9,Makueni,Transfer & EMT,Current,Maternal mortality ratio,138.08,143.86,132.30,0.00,0.00
10,Makueni,Transfer & EMT,High,Maternal mortality ratio,134.93,140.60,129.26,-3.15,-2.28
11,Makueni,Transfer & EMT,Moderate,Maternal mortality ratio,136.47,142.20,130.73,-1.61,-1.17
12,Kakamega,Transfer & EMT,Current,Maternal complications,3.11,3.27,2.95,0.00,0.00
13,Kakamega,Transfer & EMT,High,Maternal complications,3.11,3.27,2.95,0.00,0.00
14,Kakamega,Transfer & EMT,Moderate,Maternal complications,3.11,3.27,2.95,0.00,0.00
15,Kisii,Transfer & EMT,Current,Maternal complications,4.09,4.29,3.89,0.00,0.00
16,Kisii,Transfer & EMT,High,Maternal complications,4.09,4.29,3.89,0.00,0.00
17,Kisii,Transfer & EMT,Moderate,Maternal complications,4.09,4.29,3.89,0.00,0.00
18,Mombasa,Transfer & EMT,Current,Maternal complications,4.91,5.14,4.67,0.00,0.00
19,Mombasa,Transfer & EMT,High,Maternal complications,4.91,5.14,4.67,0.00,0.00
20,Mombasa,Transfer & EMT,Moderate,Maternal complications,4.91,5.14,4.67,0.00,0.00
21,Makueni,Transfer & EMT,Current,Maternal complications,4.71,4.91,4.51,0.00,0.00
22,Makueni,Transfer & EMT,High,Maternal complications,4.71,4.91,4.51,0.00,0.00
23,Makueni,Transfer & EMT,Moderate,Maternal complications,4.71,4.91,4.51,0.00,0.00

Running plots for: Blood tracking
Saved plot to: county_comparison/blood_tracking/blood_tracking_maternal_mortality_ratio_county_comparison_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/blood_tracking/kakamega/blood_tracking_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/blood_tracking/kisii/blood_tracking_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/blood_tracking/mombasa/blood_tracking_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/blood_tracking/makueni/blood_tracking_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/blood_tracking/blood_tracking_maternal_complications_county_comparison_20260813_1451.png
Saved plot to: county_comparison/blood_tracking/kakamega/blood_tracking_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/blood_tracking/kisii/blood_tracking_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/blood_tracking/mombasa/blood_tracking_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/blood_tracking/makueni/blood_tracking_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,Blood tracking,Current,Maternal mortality ratio,220.42,231.00,209.84,-8.87,-3.87
1,Kakamega,Blood tracking,High,Maternal mortality ratio,194.58,203.97,185.18,-34.71,-15.14
2,Kakamega,Blood tracking,Moderate,Maternal mortality ratio,211.37,221.53,201.21,-17.91,-7.81
3,Kisii,Blood tracking,Current,Maternal mortality ratio,61.36,64.29,58.42,-4.47,-6.79
4,Kisii,Blood tracking,High,Maternal mortality ratio,48.70,51.01,46.38,-17.12,-26.01
5,Kisii,Blood tracking,Moderate,Maternal mortality ratio,56.54,59.18,53.90,-9.28,-14.10
6,Mombasa,Blood tracking,Current,Maternal mortality ratio,56.02,58.39,53.65,-3.78,-6.33
7,Mombasa,Blood tracking,High,Maternal mortality ratio,45.49,47.40,43.58,-14.31,-23.93
8,Mombasa,Blood tracking,Moderate,Maternal mortality ratio,52.06,54.23,49.89,-7.74,-12.95
9,Makueni,Blood tracking,Current,Maternal mortality ratio,126.40,131.60,121.21,-11.67,-8.45
10,Makueni,Blood tracking,High,Maternal mortality ratio,94.70,98.61,90.79,-43.38,-31.42
11,Makueni,Blood tracking,Moderate,Maternal mortality ratio,114.60,119.26,109.95,-23.48,-17.00
12,Kakamega,Blood tracking,Current,Maternal complications,3.11,3.27,2.95,0.00,0.00
13,Kakamega,Blood tracking,High,Maternal complications,3.11,3.27,2.95,0.00,0.00
14,Kakamega,Blood tracking,Moderate,Maternal complications,3.11,3.27,2.95,0.00,0.00
15,Kisii,Blood tracking,Current,Maternal complications,4.09,4.29,3.89,0.00,0.00
16,Kisii,Blood tracking,High,Maternal complications,4.09,4.29,3.89,0.00,0.00
17,Kisii,Blood tracking,Moderate,Maternal complications,4.09,4.29,3.89,0.00,0.00
18,Mombasa,Blood tracking,Current,Maternal complications,4.91,5.14,4.67,0.00,0.00
19,Mombasa,Blood tracking,High,Maternal complications,4.91,5.14,4.67,0.00,0.00
20,Mombasa,Blood tracking,Moderate,Maternal complications,4.91,5.14,4.67,0.00,0.00
21,Makueni,Blood tracking,Current,Maternal complications,4.71,4.91,4.51,0.00,0.00
22,Makueni,Blood tracking,High,Maternal complications,4.71,4.91,4.51,0.00,0.00
23,Makueni,Blood tracking,Moderate,Maternal complications,4.71,4.91,4.51,0.00,0.00

Running plots for: All
Saved plot to: county_comparison/all/all_maternal_mortality_ratio_county_comparison_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/kakamega/all_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/all/kisii/all_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/mombasa/all_maternal_mortality_ratio_location_20260813_1451.png
Saved plot to: county_comparison/all/makueni/all_maternal_mortality_ratio_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/all_maternal_complications_county_comparison_20260813_1451.png
Saved plot to: county_comparison/all/kakamega/all_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/kisii/all_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/all/mombasa/all_maternal_complications_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/makueni/all_maternal_complications_location_20260813_1451.png
Saved plot to: county_comparison/all/all_antenatal_care_rate_county_comparison_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/kakamega/all_antenatal_care_rate_location_20260813_1451.png
Saved plot to: county_comparison/all/kisii/all_antenatal_care_rate_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/mombasa/all_antenatal_care_rate_location_20260813_1451.png
Saved plot to: county_comparison/all/makueni/all_antenatal_care_rate_location_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/all_normal_referral_county_comparison_20260813_1451.png
Saved plot to: county_comparison/all/kakamega/all_normal_referral_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/kisii/all_normal_referral_overall_by_county_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/mombasa/all_normal_referral_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/makueni/all_normal_referral_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/all_initial_delivery_l45_rate_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/kakamega/all_initial_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/kisii/all_initial_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/mombasa/all_initial_delivery_l45_rate_overall_by_county_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved plot to: county_comparison/all/makueni/all_initial_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/all_final_delivery_l45_rate_20260813_1451.png
Saved plot to: county_comparison/all/kakamega/all_final_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/kisii/all_final_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/mombasa/all_final_delivery_l45_rate_overall_by_county_20260813_1451.png
Saved plot to: county_comparison/all/makueni/all_final_delivery_l45_rate_overall_by_county_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,Outcome,mean,upper,lower,Absolute Change vs Baseline,Percent Change vs Baseline
0,Kakamega,All,Current,Maternal mortality ratio,213.90,224.20,203.61,-15.38,-6.71
1,Kakamega,All,High,Maternal mortality ratio,113.20,118.75,107.65,-116.09,-50.63
2,Kakamega,All,Moderate,Maternal mortality ratio,171.47,179.48,163.46,-57.81,-25.21
3,Kisii,All,Current,Maternal mortality ratio,54.63,57.09,52.17,-11.19,-17.00
4,Kisii,All,High,Maternal mortality ratio,23.11,24.17,22.05,-42.71,-64.89
...,...,...,...,...,...,...,...,...,...
67,Mombasa,All,High,Final delivery at L4/5,71.66,71.69,71.64,2.30,3.32
68,Mombasa,All,Moderate,Final delivery at L4/5,70.36,70.38,70.34,1.00,1.44
69,Makueni,All,Current,Final delivery at L4/5,65.95,65.98,65.92,0.24,0.36
70,Makueni,All,High,Final delivery at L4/5,72.50,72.50,72.50,6.79,10.33
71,Makueni,All,Moderate,Final delivery at L4/5,72.00,72.02,71.99,6.29,9.58

In [9]:
# =========================================================
# COUNTY % CHANGE SUBPLOT GRIDS
# =========================================================

for outcome in BASE_OUTCOMES:
    exclude = PCT_CHANGE_EXCLUDE_INTERVENTIONS.get(outcome["summary_name"], [])
    grid = plot_county_pct_change_subplots(outcome, exclude_interventions=exclude)
    display(grid.head(12))

PROMPTS_EXTRA_OUTCOMES = [
    o for o in INTERVENTION_CONFIGS["prompts"]["outcomes_to_plot"]
    if o["summary_name"] not in {x["summary_name"] for x in BASE_OUTCOMES}
] + [
    {
        "summary_name": loc_plot["plot_title"],
        "outcome_col": loc_plot["rate_col"],
        "multiplier": 100,
        "plot_name": loc_plot["plot_name"],
        "lower_is_better": False,
    }
    for loc_plot in INTERVENTION_CONFIGS["prompts"].get("location_distribution_plots", [])
]

for outcome in PROMPTS_EXTRA_OUTCOMES:
    grid = build_pct_change_grid(outcome)
    grid = grid[grid["Intervention"] == "PROMPTS"]
    if grid.empty:
        continue

    fig, axes = plt.subplots(1, len(COUNTIES), figsize=(3.0 * len(COUNTIES) + 1.0, 3.8), sharey=True)
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    if len(COUNTIES) == 1:
        axes = [axes]

    bar_colors = [SCENARIO_COLORS[l] for l in CHANGE_LEVEL_LABELS]
    y_limit = max(5, np.ceil(grid["Percent change vs baseline"].abs().max() / 5) * 5)

    for c, county in enumerate(COUNTIES):
        ax = axes[c]
        ax.set_facecolor(SDR_COLORS["card"])
        cell = grid[grid["County"] == county].set_index("Scenario Label").reindex(CHANGE_LEVEL_LABELS)
        values = cell["Percent change vs baseline"].to_numpy(dtype=float)
        x = np.arange(len(CHANGE_LEVEL_LABELS))
        ax.bar(x, values, color=bar_colors, width=0.62)
        for bar, value in zip(ax.patches, values):
            if pd.notna(value):
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + np.sign(value) * 0.8,
                    f"{value:.1f}%",
                    ha="center",
                    va="bottom" if value >= 0 else "top",
                    fontsize=8,
                )
        ax.axhline(0, color=SDR_COLORS["ink_muted"], linewidth=0.8)
        ax.set_ylim(-y_limit, y_limit)
        ax.set_xticks(x)
        ax.set_xticklabels(CHANGE_LEVEL_LABELS, fontsize=8, rotation=35, ha="right")
        ax.set_title(county, fontsize=11)
        ax.grid(axis="y", alpha=0.4)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

    fig.suptitle(
        f"PROMPTS — {outcome['summary_name']}: percent change from baseline by county",
        fontsize=15,
        y=1.02,
    )
    plt.tight_layout()

    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    summary_dir = PLOTS_ROOT / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)
    plot_name = f"prompts_{outcome['plot_name']}_county_pct_change_subplots"
    png_path = summary_dir / f"{plot_name}_{timestamp}.png"
    csv_path = summary_dir / f"{plot_name}_{timestamp}.csv"
    fig.savefig(png_path, dpi=300, bbox_inches="tight", facecolor=SDR_COLORS["paper"])
    grid.round(2).to_csv(csv_path, index=False)
    plt.show()
    print(f"Saved PROMPTS pct-change subplots to: {png_path}")

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/3163252819.py:157: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

   Intervention    County Scenario Label  Percent change vs baseline
0       MENTORS  Kakamega        Current                   -3.413420
1       MENTORS  Kakamega       Moderate                   -5.483362
2       MENTORS  Kakamega           High                   -7.293623
3       MENTORS     Kisii        Current                   -9.743982
4       MENTORS     Kisii       Moderate                  -13.060757
5       MENTORS     Kisii           High                  -16.713794
6       MENTORS   Mombasa        Current                   -7.266764
7       MENTORS   Mombasa       Moderate                  -10.822473
8       MENTORS   Mombasa           High                  -14.145163
9       MENTORS   Makueni        Current                   -9.709047
10      MENTORS   Makueni       Moderate                  -12.788171
11      MENTORS   Makueni           High                  -16.275372

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/3163252819.py:157: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

   Intervention    County Scenario Label  Percent change vs baseline
0       MENTORS  Kakamega        Current                   -6.943072
1       MENTORS  Kakamega       Moderate                  -11.726108
2       MENTORS  Kakamega           High                  -15.885298
3       MENTORS     Kisii        Current                  -15.449506
4       MENTORS     Kisii       Moderate                  -20.731268
5       MENTORS     Kisii           High                  -26.132048
6       MENTORS   Mombasa        Current                  -13.309721
7       MENTORS   Mombasa       Moderate                  -18.336122
8       MENTORS   Mombasa           High                  -23.212875
9       MENTORS   Makueni        Current                  -16.739407
10      MENTORS   Makueni       Moderate                  -21.995671
11      MENTORS   Makueni           High                  -27.826038

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/1650466808.py:79: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved PROMPTS pct-change subplots to: summary/prompts_antenatal_care_rate_county_pct_change_subplots_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/1650466808.py:79: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/1650466808.py:79: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Saved PROMPTS pct-change subplots to: summary/prompts_normal_referral_county_pct_change_subplots_20260813_1451.png
Saved PROMPTS pct-change subplots to: summary/prompts_initial_delivery_l45_rate_county_pct_change_subplots_20260813_1451.png
Saved PROMPTS pct-change subplots to: summary/prompts_final_delivery_l45_rate_county_pct_change_subplots_20260813_1451.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/1650466808.py:79: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [10]:
# =========================================================
# COUNTY % CHANGE HEATMAPS (compact alternative to bar subplots)
# =========================================================

for outcome in BASE_OUTCOMES:
    exclude = PCT_CHANGE_EXCLUDE_INTERVENTIONS.get(outcome["summary_name"], [])
    plot_county_pct_change_heatmap(outcome, exclude_interventions=exclude)

plot_prompts_extra_pct_change_heatmap(PROMPTS_EXTRA_OUTCOMES)

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/3163252819.py:258: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/3163252819.py:258: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/3163252819.py:258: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,Intervention,County,Scenario Label,Percent change vs baseline,Outcome,lower_is_better
0,PROMPTS,Kakamega,Current,0.000000,Antenatal care rate,False
1,PROMPTS,Kakamega,Moderate,9.014359,Antenatal care rate,False
2,PROMPTS,Kakamega,High,33.303828,Antenatal care rate,False
3,PROMPTS,Kisii,Current,0.294686,Antenatal care rate,False
4,PROMPTS,Kisii,Moderate,8.954439,Antenatal care rate,False
5,PROMPTS,Kisii,High,33.399095,Antenatal care rate,False
6,PROMPTS,Mombasa,Current,0.364256,Antenatal care rate,False
7,PROMPTS,Mombasa,Moderate,9.066403,Antenatal care rate,False
8,PROMPTS,Mombasa,High,33.439467,Antenatal care rate,False
9,PROMPTS,Makueni,Current,0.228116,Antenatal care rate,False
10,PROMPTS,Makueni,Moderate,8.988910,Antenatal care rate,False
11,PROMPTS,Makueni,High,33.334725,Antenatal care rate,False
12,PROMPTS,Kakamega,Current,0.000000,Normal referral,False
13,PROMPTS,Kakamega,Moderate,10.561584,Normal referral,False
14,PROMPTS,Kakamega,High,35.394593,Normal referral,False
15,PROMPTS,Kisii,Current,0.282134,Normal referral,False
16,PROMPTS,Kisii,Moderate,5.949490,Normal referral,False
17,PROMPTS,Kisii,High,12.319707,Normal referral,False
18,PROMPTS,Mombasa,Current,0.483858,Normal referral,False
19,PROMPTS,Mombasa,Moderate,1.543979,Normal referral,False
20,PROMPTS,Mombasa,High,3.761132,Normal referral,False
21,PROMPTS,Makueni,Current,0.444550,Normal referral,False
22,PROMPTS,Makueni,Moderate,8.387345,Normal referral,False
23,PROMPTS,Makueni,High,18.387303,Normal referral,False
24,PROMPTS,Kakamega,Current,0.000000,Initial delivery at L4/5,False
25,PROMPTS,Kakamega,Moderate,10.561584,Initial delivery at L4/5,False
26,PROMPTS,Kakamega,High,35.394593,Initial delivery at L4/5,False
27,PROMPTS,Kisii,Current,0.282134,Initial delivery at L4/5,False
28,PROMPTS,Kisii,Moderate,5.949490,Initial delivery at L4/5,False
29,PROMPTS,Kisii,High,12.319707,Initial delivery at L4/5,False
30,PROMPTS,Mombasa,Current,0.483858,Initial delivery at L4/5,False
31,PROMPTS,Mombasa,Moderate,1.543979,Initial delivery at L4/5,False
32,PROMPTS,Mombasa,High,3.761132,Initial delivery at L4/5,False
33,PROMPTS,Makueni,Current,0.444550,Initial delivery at L4/5,False
34,PROMPTS,Makueni,Moderate,8.387345,Initial delivery at L4/5,False
35,PROMPTS,Makueni,High,18.387303,Initial delivery at L4/5,False
36,PROMPTS,Kakamega,Current,0.000000,Final delivery at L4/5,False
37,PROMPTS,Kakamega,Moderate,9.146895,Final delivery at L4/5,False
38,PROMPTS,Kakamega,High,31.127935,Final delivery at L4/5,False
39,PROMPTS,Kisii,Current,0.235634,Final delivery at L4/5,False
40,PROMPTS,Kisii,Moderate,4.970882,Final delivery at L4/5,False
41,PROMPTS,Kisii,High,6.719133,Final delivery at L4/5,False
42,PROMPTS,Mombasa,Current,0.401713,Final delivery at L4/5,False
43,PROMPTS,Mombasa,Moderate,1.344981,Final delivery at L4/5,False
44,PROMPTS,Mombasa,High,3.264378,Final delivery at L4/5,False
45,PROMPTS,Makueni,Current,0.364440,Final delivery at L4/5,False
46,PROMPTS,Makueni,Moderate,6.862165,Final delivery at L4/5,False
47,PROMPTS,Makueni,High,10.330966,Final delivery at L4/5,False

In [11]:
# =========================================================
# VALIDATION
# =========================================================

checks = [
    ("Kakamega", "mentors", "mentors_current", "maternal_deaths_per_100k", 1),
    ("Kisii", "mentors", "mentors_current", "maternal_deaths_per_100k", 1),
    ("Mombasa", "fqa", "fqa_high", "maternal_deaths_per_100k", 1),
]

validation_rows = []
for county, file_key, scenario, col, multiplier in checks:
    mean_df = pd.read_csv(resolve_county_csv(COUNTY_DIRS[county], "scenario_mean_results.csv"))
    intervention_name = INTERVENTION_CONFIGS[file_key]["intervention_name"]
    subset = load_intervention_run_data(file_key, intervention_name)
    subset = subset[(subset["County"] == county) & (subset["scenario"] == scenario)]

    notebook_mean = (subset[col] * multiplier).mean()
    reference_mean = mean_df.loc[mean_df["scenario"] == scenario, col].iloc[0] * multiplier

    validation_rows.append({
        "county": county,
        "scenario": scenario,
        "notebook_mean": round(notebook_mean, 4),
        "scenario_mean_results": round(reference_mean, 4),
        "difference": round(notebook_mean - reference_mean, 6),
    })

validation_table = pd.DataFrame(validation_rows)
display(validation_table)

if (validation_table["difference"].abs() > 1e-6).any():
    print("Warning: notebook means differ from scenario_mean_results.csv")
else:
    print("Validation passed")

     county         scenario  notebook_mean  scenario_mean_results  difference
0  Kakamega  mentors_current       221.4595               221.4595         0.0
1     Kisii  mentors_current        59.4088                59.4088        -0.0
2   Mombasa         fqa_high        55.5143                55.5143         0.0

Validation passed

In [12]:
# =========================================================
# FQA DIAGNOSTIC: ONE COUNTY / ONE INTERVENTION FAMILY
# =========================================================
# Choose one county, then set RUN_FQA_DIAGNOSTIC = True to regenerate this
# diagnostic batch. Results are saved separately from scenario_comparison.py.

import scenario_comparison as sc
import parameter_loader
from global_func import reset_E, reset_HSS, reset_S, reset_flags
from model_run import run_model_dash
from parameter_loader import calculate_derived_parameters, get_parameters, get_slider_params

FQA_DIAGNOSTIC_COUNTY = "Kisii"  # choose: "Kakamega", "Kisii", "Mombasa", "Makueni"
RUN_FQA_DIAGNOSTIC = True
PLOT_FQA_DIAGNOSTIC = True

FQA_DIAGNOSTIC_SKIP_INITIAL_RUNS = 200
FQA_DIAGNOSTIC_ANALYSIS_RUNS = 200
FQA_DIAGNOSTIC_FIRST_ANALYSIS_RUN = FQA_DIAGNOSTIC_SKIP_INITIAL_RUNS + 1
FQA_DIAGNOSTIC_N_RUNS = FQA_DIAGNOSTIC_SKIP_INITIAL_RUNS + FQA_DIAGNOSTIC_ANALYSIS_RUNS

FQA_DIAGNOSTIC_SCENARIOS = [
    {"scenario": "fqa_base", "intervention": "FQA", "level": "base",
     "description": "PULSE current; FQA off; all single interventions on"},
    {"scenario": "fqa_current", "intervention": "FQA", "level": "current",
     "description": "County-specific current FQA index; PULSE current; all single interventions on; 10% amplification"},
    {"scenario": "fqa_moderate", "intervention": "FQA", "level": "moderate",
     "description": "50% FQA implementation index; PULSE current; all single interventions on; 10% amplification"},
    {"scenario": "fqa_high", "intervention": "FQA", "level": "high",
     "description": "95% FQA implementation index; PULSE current; all single interventions on; 30% amplification"},
]

FQA_DIAGNOSTIC_OUTCOMES = [
    {
        "summary_name": "Maternal mortality ratio",
        "outcome_col": "maternal_deaths_per_100k",
        "multiplier": 1,
        "ylabel": "MMR per 100,000 live births",
        "plot_name": "maternal_mortality_ratio",
    },
    {
        "summary_name": "Maternal complications",
        "outcome_col": "severe_complication",
        "multiplier": 100,
        "ylabel": "Maternal complications (%)",
        "plot_name": "maternal_complications",
    },
]


def _fqa_diagnostic_county_slug(county):
    if county not in COUNTY_FOLDER_SLUGS:
        raise ValueError(f"Choose one of {list(COUNTY_FOLDER_SLUGS)}; got {county!r}")
    return COUNTY_FOLDER_SLUGS[county]


def fqa_diagnostic_output_dir(county=FQA_DIAGNOSTIC_COUNTY):
    slug = _fqa_diagnostic_county_slug(county)
    return DATA_ROOT / f"fqa_diagnostic_results_{slug}"


def run_fqa_diagnostic(county=FQA_DIAGNOSTIC_COUNTY):
    county_slug = _fqa_diagnostic_county_slug(county)
    output_dir = fqa_diagnostic_output_dir(county)
    output_dir.mkdir(parents=True, exist_ok=True)

    parameter_loader.WORKBOOK_PATH = sc.WORKBOOK_PATH
    slider_params = get_slider_params(county=county_slug)

    rows = []
    location_rows = []
    run_indices = range(FQA_DIAGNOSTIC_FIRST_ANALYSIS_RUN - 1, FQA_DIAGNOSTIC_N_RUNS)

    for completed_runs, run in enumerate(run_indices, start=1):
        parameter_seed = sc.BASE_SEED + run
        month_seeds = np.arange(parameter_seed, parameter_seed + sc.N_MONTHS, dtype=int)

        for scenario_def in FQA_DIAGNOSTIC_SCENARIOS:
            scenario = scenario_def["scenario"]

            param = get_parameters(county=county_slug, seed=parameter_seed)
            param = calculate_derived_parameters(param)
            param.update({
                "E": reset_E(),
                "S": reset_S(slider_params),
                "HSS": reset_HSS(slider_params),
            })

            flags = reset_flags()
            sc.configure_scenario(scenario, param, flags, slider_params)

            _, individuals, _ = run_model_dash(
                param,
                flags,
                n_months=sc.N_MONTHS,
                int_period=sc.N_MONTHS,
                base_seed=month_seeds,
            )

            rows.append({
                "scenario": scenario,
                "intervention": scenario_def["intervention"],
                "level": scenario_def["level"],
                "run": run + 1,
                **sc.summarize(individuals),
            })

            for location_result in sc.summarize_by_location(individuals):
                location_rows.append({
                    "scenario": scenario,
                    "intervention": scenario_def["intervention"],
                    "level": scenario_def["level"],
                    "run": run + 1,
                    **location_result,
                })

        if completed_runs % 10 == 0 or completed_runs == 1:
            print(
                f"{county}: completed {completed_runs}/{FQA_DIAGNOSTIC_ANALYSIS_RUNS} "
                f"diagnostic runs using run {run + 1}/{FQA_DIAGNOSTIC_N_RUNS}",
                flush=True,
            )

    scenario_definitions = pd.DataFrame(FQA_DIAGNOSTIC_SCENARIOS)
    run_results = pd.DataFrame(rows)
    location_run_results = pd.DataFrame(location_rows)

    metric_columns = [
        c for c in run_results.columns
        if c not in {"scenario", "intervention", "level", "run"}
    ]
    mean_results = (
        run_results
        .groupby(["scenario", "intervention", "level"], sort=False)[metric_columns]
        .mean()
        .reset_index()
    )

    location_keys = ["scenario", "intervention", "level", "location", "location_code"]
    location_metric_columns = [
        c for c in location_run_results.columns
        if c not in {*location_keys, "run"}
    ]
    location_mean_results = (
        location_run_results
        .groupby(location_keys, sort=False)[location_metric_columns]
        .mean()
        .reset_index()
    )

    baseline = mean_results.loc[
        mean_results["scenario"] == "fqa_base", metric_columns
    ].iloc[0]
    differences_from_fqa_base = mean_results.copy()
    differences_from_fqa_base[metric_columns] = (
        mean_results[metric_columns].to_numpy() - baseline.to_numpy()
    )
    differences_from_fqa_base.insert(3, "comparison_baseline", "fqa_base")

    baseline_by_location = location_mean_results.loc[
        location_mean_results["scenario"] == "fqa_base",
        ["location_code", *location_metric_columns],
    ].set_index("location_code")

    location_differences_from_fqa_base = location_mean_results.copy()
    for index, row in location_differences_from_fqa_base.iterrows():
        baseline_location = baseline_by_location.loc[row["location_code"]]
        location_differences_from_fqa_base.loc[index, location_metric_columns] = (
            row[location_metric_columns].to_numpy(dtype=float)
            - baseline_location.to_numpy(dtype=float)
        )
    location_differences_from_fqa_base.insert(3, "comparison_baseline", "fqa_base")

    scenario_definitions.to_csv(output_dir / "scenario_definitions.csv", index=False)
    run_results.to_csv(output_dir / "scenario_run_results.csv", index=False)
    location_run_results.to_csv(output_dir / "scenario_location_run_results.csv", index=False)
    mean_results.to_csv(output_dir / "scenario_mean_results.csv", index=False)
    location_mean_results.to_csv(output_dir / "scenario_location_mean_results.csv", index=False)
    differences_from_fqa_base.to_csv(output_dir / "scenario_differences_from_fqa_base.csv", index=False)
    location_differences_from_fqa_base.to_csv(
        output_dir / "scenario_location_differences_from_fqa_base.csv",
        index=False,
    )

    print(f"Saved FQA diagnostic outputs to: {output_dir}")

    return {
        "scenario_definitions": scenario_definitions,
        "run_results": run_results,
        "location_run_results": location_run_results,
        "mean_results": mean_results,
        "location_mean_results": location_mean_results,
        "differences_from_fqa_base": differences_from_fqa_base,
        "location_differences_from_fqa_base": location_differences_from_fqa_base,
    }


def load_fqa_diagnostic_results(county=FQA_DIAGNOSTIC_COUNTY):
    output_dir = fqa_diagnostic_output_dir(county)
    required = {
        "scenario_definitions": output_dir / "scenario_definitions.csv",
        "run_results": output_dir / "scenario_run_results.csv",
        "location_run_results": output_dir / "scenario_location_run_results.csv",
        "mean_results": output_dir / "scenario_mean_results.csv",
        "location_mean_results": output_dir / "scenario_location_mean_results.csv",
        "differences_from_fqa_base": output_dir / "scenario_differences_from_fqa_base.csv",
        "location_differences_from_fqa_base": output_dir / "scenario_location_differences_from_fqa_base.csv",
    }

    missing = [path for path in required.values() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "No saved FQA diagnostic results found. "
            "Set RUN_FQA_DIAGNOSTIC = True and rerun this cell. "
            f"Missing: {missing[0]}"
        )

    return {name: pd.read_csv(path) for name, path in required.items()}


def _prepare_fqa_diagnostic_run_data(results, county=FQA_DIAGNOSTIC_COUNTY):
    df = results["run_results"].copy()
    df["County"] = county
    df["Scenario Label"] = df["level"].map(LEVEL_TO_LABEL)
    df["Intervention"] = "FQA"
    df["Run"] = df["run"]
    return df


def _prepare_fqa_diagnostic_location_data(results, county=FQA_DIAGNOSTIC_COUNTY):
    df = results["location_run_results"].copy()
    df["County"] = county
    df["Scenario Label"] = df["level"].map(LEVEL_TO_LABEL)
    df["Intervention"] = "FQA"
    df["Run"] = df["run"]
    df["Delivery Location"] = df["location"].astype(str).str.strip()
    return df


def plot_fqa_diagnostic_outcome(results, outcome_spec, county=FQA_DIAGNOSTIC_COUNTY):
    diagnostic_df = _prepare_fqa_diagnostic_run_data(results, county)
    summary = summarize_preaggregated_outcome(
        diagnostic_df,
        outcome_spec["outcome_col"],
        outcome_spec["multiplier"],
        outcome_spec["summary_name"],
        ["County", "Intervention", "Scenario Label"],
    )

    plot_df = (
        summary[summary["County"] == county]
        .set_index("Scenario Label")
        .reindex(SCENARIOS)
    )
    plot_df = plot_df[pd.notna(plot_df["mean"])]

    fig, ax = plt.subplots(figsize=(8.8, 5.2))
    fig.patch.set_facecolor(SDR_COLORS["paper"])
    ax.set_facecolor(SDR_COLORS["card"])

    x = np.arange(len(plot_df))
    bars = ax.bar(
        x,
        plot_df["mean"],
        yerr=plot_df["ci95"],
        capsize=2,
        color=[SCENARIO_COLORS[label] for label in plot_df.index],
        edgecolor="none",
        alpha=0.95,
        error_kw={"elinewidth": 1, "ecolor": SDR_COLORS["ink_soft"], "capthick": 1},
    )
    _annotate_bars(ax, bars, plot_df["mean"])

    ax.set_title(
        f"FQA diagnostic: {outcome_spec['summary_name']} — {county}",
        fontsize=17,
        pad=14,
        color=SDR_COLORS["ink"],
    )
    ax.set_ylabel(outcome_spec["ylabel"], fontsize=11)
    ax.set_xlabel("Scenario", fontsize=11)
    ax.set_xticks(x)
    ax.set_xticklabels(plot_df.index, fontsize=10)
    _style_axes(ax)
    ax.margins(y=0.22)
    plt.tight_layout()

    plot_dir = fqa_diagnostic_output_dir(county) / "plots"
    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    _save_plot(
        fig,
        plot_dir,
        "fqa_diagnostic",
        f"overall_{outcome_spec['plot_name']}",
        timestamp,
    )

    return summary


def plot_fqa_diagnostic_location_outcome(results, outcome_spec, county=FQA_DIAGNOSTIC_COUNTY):
    diagnostic_location_df = _prepare_fqa_diagnostic_location_data(results, county)
    summary = summarize_preaggregated_outcome(
        diagnostic_location_df,
        outcome_spec["outcome_col"],
        outcome_spec["multiplier"],
        outcome_spec["summary_name"],
        ["County", "Intervention", "Delivery Location", "Scenario Label"],
    )

    plot_dir = fqa_diagnostic_output_dir(county) / "plots"
    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d_%H%M")
    plot_outcome_by_location(
        summary,
        outcome_spec["summary_name"],
        outcome_spec["ylabel"],
        f"fqa_diagnostic_location_{outcome_spec['plot_name']}",
        "FQA diagnostic",
        county,
        "fqa_diagnostic",
        plot_dir,
        timestamp,
    )

    return summary


if RUN_FQA_DIAGNOSTIC:
    fqa_diagnostic_results = run_fqa_diagnostic(FQA_DIAGNOSTIC_COUNTY)
else:
    fqa_diagnostic_results = load_fqa_diagnostic_results(FQA_DIAGNOSTIC_COUNTY)
    print(f"Loaded saved FQA diagnostic outputs from: {fqa_diagnostic_output_dir(FQA_DIAGNOSTIC_COUNTY)}")

if PLOT_FQA_DIAGNOSTIC and fqa_diagnostic_results is not None:
    for outcome in FQA_DIAGNOSTIC_OUTCOMES:
        display(plot_fqa_diagnostic_outcome(fqa_diagnostic_results, outcome, FQA_DIAGNOSTIC_COUNTY))
        display(plot_fqa_diagnostic_location_outcome(fqa_diagnostic_results, outcome, FQA_DIAGNOSTIC_COUNTY))

Kisii: completed 1/200 diagnostic runs using run 201/400
Kisii: completed 10/200 diagnostic runs using run 210/400
Kisii: completed 20/200 diagnostic runs using run 220/400
Kisii: completed 30/200 diagnostic runs using run 230/400
Kisii: completed 40/200 diagnostic runs using run 240/400

/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)

Kisii: completed 50/200 diagnostic runs using run 250/400
Kisii: completed 60/200 diagnostic runs using run 260/400
Kisii: completed 70/200 diagnostic runs using run 270/400
Kisii: completed 80/200 diagnostic runs using run 280/400
Kisii: completed 90/200 diagnostic runs using run 290/400
Kisii: completed 100/200 diagnostic runs using run 300/400
Kisii: completed 110/200 diagnostic runs using run 310/400
Kisii: completed 120/200 diagnostic runs using run 320/400
Kisii: completed 130/200 diagnostic runs using run 330/400

/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)
/Users/poppy/Documents/GitHub/SDR-Dashboard-2026-main/global_func.py:21: RuntimeWarning: The iteration is not making good progress, as measured by the
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)

Kisii: completed 140/200 diagnostic runs using run 340/400
Kisii: completed 150/200 diagnostic runs using run 350/400
Kisii: completed 160/200 diagnostic runs using run 360/400
Kisii: completed 170/200 diagnostic runs using run 370/400
Kisii: completed 180/200 diagnostic runs using run 380/400
Kisii: completed 190/200 diagnostic runs using run 390/400
Kisii: completed 200/200 diagnostic runs using run 400/400
Saved FQA diagnostic outputs to: fqa_diagnostic_results_kisii
Saved plot to: fqa_diagnostic_results_kisii/plots/fqa_diagnostic_overall_maternal_mortality_ratio_20260813_1457.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,mean,sd,n_runs,ci95,lower,upper,Outcome
0,Kisii,FQA,Baseline,59.972232,22.025829,200,3.052624,56.919608,63.024856,Maternal mortality ratio
1,Kisii,FQA,Current,59.942050,22.031964,200,3.053474,56.888576,62.995524,Maternal mortality ratio
2,Kisii,FQA,High,58.729728,21.709412,200,3.008771,55.720957,61.738499,Maternal mortality ratio
3,Kisii,FQA,Moderate,59.222705,21.755108,200,3.015104,56.207601,62.237809,Maternal mortality ratio

Saved plot to: fqa_diagnostic_results_kisii/plots/kisii/fqa_diagnostic_fqa_diagnostic_location_maternal_mortality_ratio_20260813_1457.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Delivery Location,Scenario Label,mean,sd,n_runs,ci95,lower,upper,Outcome
0,Kisii,FQA,Home,Baseline,475.704010,177.804195,200,24.642404,451.061606,500.346415,Maternal mortality ratio
1,Kisii,FQA,Home,Current,475.704010,177.804195,200,24.642404,451.061606,500.346415,Maternal mortality ratio
2,Kisii,FQA,Home,High,481.094395,177.621259,200,24.617051,456.477345,505.711446,Maternal mortality ratio
3,Kisii,FQA,Home,Moderate,474.114404,173.645319,200,24.066013,450.048391,498.180418,Maternal mortality ratio
4,Kisii,FQA,L2/3,Baseline,62.257932,24.580382,200,3.406667,58.851264,65.664599,Maternal mortality ratio
5,Kisii,FQA,L2/3,Current,62.235361,24.585890,200,3.407431,58.827930,65.642792,Maternal mortality ratio
6,Kisii,FQA,L2/3,High,55.126513,25.615886,200,3.550181,51.576332,58.676693,Maternal mortality ratio
7,Kisii,FQA,L2/3,Moderate,60.381374,24.552215,200,3.402763,56.978610,63.784137,Maternal mortality ratio
8,Kisii,FQA,L4,Baseline,13.257506,7.114601,200,0.986033,12.271473,14.243539,Maternal mortality ratio
9,Kisii,FQA,L4,Current,13.246755,7.106927,200,0.984970,12.261785,14.231725,Maternal mortality ratio
10,Kisii,FQA,L4,High,14.037412,7.644041,200,1.059410,12.978002,15.096822,Maternal mortality ratio
11,Kisii,FQA,L4,Moderate,13.179847,6.991827,200,0.969018,12.210829,14.148865,Maternal mortality ratio
12,Kisii,FQA,L5,Baseline,48.594338,23.310123,200,3.230618,45.363720,51.824957,Maternal mortality ratio
13,Kisii,FQA,L5,Current,48.511020,23.321824,200,3.232240,45.278780,51.743259,Maternal mortality ratio
14,Kisii,FQA,L5,High,47.201795,22.188388,200,3.075154,44.126642,50.276949,Maternal mortality ratio
15,Kisii,FQA,L5,Moderate,47.748479,23.405328,200,3.243813,44.504666,50.992292,Maternal mortality ratio

Saved plot to: fqa_diagnostic_results_kisii/plots/fqa_diagnostic_overall_maternal_complications_20260813_1457.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Scenario Label,mean,sd,n_runs,ci95,lower,upper,Outcome
0,Kisii,FQA,Baseline,3.473309,1.241516,200,0.172065,3.301243,3.645374,Maternal complications
1,Kisii,FQA,Current,3.472519,1.241267,200,0.172031,3.300488,3.644550,Maternal complications
2,Kisii,FQA,High,3.410791,1.233725,200,0.170986,3.239806,3.581777,Maternal complications
3,Kisii,FQA,Moderate,3.441648,1.237546,200,0.171515,3.270132,3.613163,Maternal complications

Saved plot to: fqa_diagnostic_results_kisii/plots/kisii/fqa_diagnostic_fqa_diagnostic_location_maternal_complications_20260813_1457.png

/var/folders/70/863t0mz55rbbjfq24prwn94m0000gn/T/ipykernel_30249/191103605.py:59: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,County,Intervention,Delivery Location,Scenario Label,mean,sd,n_runs,ci95,lower,upper,Outcome
0,Kisii,FQA,Home,Baseline,3.712427,1.257187,200,0.174237,3.538190,3.886664,Maternal complications
1,Kisii,FQA,Home,Current,3.712937,1.257597,200,0.174294,3.538643,3.887231,Maternal complications
2,Kisii,FQA,Home,High,3.734873,1.261071,200,0.174775,3.560097,3.909648,Maternal complications
3,Kisii,FQA,Home,Moderate,3.707422,1.255849,200,0.174052,3.533371,3.881474,Maternal complications
4,Kisii,FQA,L2/3,Baseline,3.599867,1.186825,200,0.164486,3.435381,3.764352,Maternal complications
5,Kisii,FQA,L2/3,Current,3.599839,1.186689,200,0.164467,3.435372,3.764305,Maternal complications
6,Kisii,FQA,L2/3,High,3.548003,1.202043,200,0.166595,3.381409,3.714598,Maternal complications
7,Kisii,FQA,L2/3,Moderate,3.579627,1.196125,200,0.165774,3.413853,3.745402,Maternal complications
8,Kisii,FQA,L4,Baseline,1.927914,0.736408,200,0.102061,1.825853,2.029975,Maternal complications
9,Kisii,FQA,L4,Current,1.927101,0.736073,200,0.102015,1.825087,2.029116,Maternal complications
10,Kisii,FQA,L4,High,1.888605,0.729238,200,0.101067,1.787538,1.989672,Maternal complications
11,Kisii,FQA,L4,Moderate,1.908637,0.732516,200,0.101521,1.807115,2.010158,Maternal complications
12,Kisii,FQA,L5,Baseline,6.325985,2.225404,200,0.308425,6.017560,6.634410,Maternal complications
13,Kisii,FQA,L5,Current,6.324201,2.225006,200,0.308370,6.015831,6.632572,Maternal complications
14,Kisii,FQA,L5,High,6.188939,2.197224,200,0.304520,5.884420,6.493459,Maternal complications
15,Kisii,FQA,L5,Moderate,6.253832,2.210097,200,0.306304,5.947528,6.560136,Maternal complications